### ISSUE TITLE
struggling to install the package

### ISSUE THREAD

**Issue by find19** [jjf234/roll#11]
Installation failed: Could not find build tools necessary to build roll

**Comment by mcooganj** [comment]
Have you installed Rtools?

**Comment by find19** [comment]
when i'm trying to get it, i'm getting following message...

> devtools::install_github("jjf234/roll")
Downloading GitHub repo jjf234/roll@master
from URL https://api.github.com/repos/jjf234/roll/zipball/master
trying URL 'https://cran.rstudio.com/bin/windows/Rtools/Rtools34.exe'
Content type 'application/x-msdos-program' length 108085090 bytes (103.1 MB)
downloaded 103.1 MB

**Installation failed: Could not find build tools necessary to build roll**

I got **tools** for Package Development (**3.4.1**)

**Comment by mcooganj** [comment]
Try uninstalling and reinstalling Rtools.

**Comment by jjf234** [comment]
As suggested, if you are on Windows, you should try uninstalling and reinstalling Rtools: https://cran.r-project.org/bin/windows/Rtools/. For more information, and instructions for other systems, see: https://support.rstudio.com/hc/en-us/articles/200486498-Package-Development-Prerequisites

**Comment by jjf234** [comment]
Otherwise there is something in your set-up preventing you from using the compiler you've installed to build R packages. I'm going to close this issue though because it isn't something I can fix by changing `roll`'s source code.
