### ISSUE TITLE
Any chance to get back roll_eigen, roll_vif, and roll_pcr?

### ISSUE THREAD

**Issue by SamoPP** [jjf234/roll#12]
Thanks for this very powerful package.

Would it be possible to add back roll_eigen, roll_vif, and roll_pcr?

Thanks.

**Comment by jjf234** [comment]
Thanks! I removed those functions for a few reasons. First, I surveyed other rolling packages and found out the functions that were most common. Not only did that reveal the functions I removed were not common (or even available in other packages), it also highlighted a few gaps that need to be addressed instead (see #4). Second, I ran a cost-benefit analysis for each function and concluded there was low marginal benefit to some of these functions, especially when the `roll` package does most of the heavy-lifting and actually gives you the necessary inputs to use in another function. For example, you can run `eigen` on the outputs from `roll_cov` or transform the `r-squareds` from `roll_lm` to get the same results as `roll_eigen` and `roll_vif`, respectively. Finally, I increased the standards of my unit tests and felt more comfortable using base functions for that part of the process, and also improves consistency. For these reasons, I don’t have plans to include those functions in the `roll` package. That being said, the source is archived and available on CRAN, if needed: https://cran.r-project.org/src/contrib/Archive/roll/

**Comment by kismsu** [comment]
Shame, just remembered about your R/Finance presentation and wanted to use roll_pcr
