### ISSUE TITLE
roll_any() and roll_all()

### ISSUE THREAD

**Issue by hadley** [jjf234/roll#14]
Would you consider extending roll to also think about logical vectors? `roll_any()` and `roll_all()` are admittedly esoteric, but can sometimes be useful, and would complete the matrix of summary functions at https://github.com/r-lib/vctrs/issues/9

**Comment by jjf234** [comment]
Thanks, that's an interesting suggestion. Just so I understand what you’re thinking, here’s an example of how I’d approach it in base R:

```
library(roll)
library(xts)

n_vars <- 3
n_obs <- 15
x <- matrix(sample(c(TRUE, FALSE), (n_obs * n_vars), replace = TRUE),
            nrow = n_obs, ncol = n_vars)

rollapplyr(x, 5, any)
rollapplyr(x, 5, all)
```

If so, I can see it fitting within my framework and existing arguments: `min_obs`, `complete_obs`, `na_restore`. An exception is the `weights` argument but that wouldn't make sense with a logical matrix anyway. Will look into it further.

**Comment by hadley** [comment]
Yeah, exactly.

**Comment by jjf234** [comment]
I have added both `roll_any` and `roll_all` in the development version. Here's an example:

```
# devtools::install_github("jjf234/roll")

library(roll)
library(xts)
library(testthat)

n_vars <- 30
n_obs <- 1500
x <- matrix(rnorm(n_obs * n_vars), nrow = n_obs, ncol = n_vars)

# rolling any ('min_obs = 1' equivalent to 'partial = TRUE')
expect_equivalent(roll_any(x < 0, 5, min_obs = 1),
                  rollapplyr(x < 0, 5, any, partial = TRUE))

# rolling all
expect_equivalent(roll_all(x < 0, 5, min_obs = 1),
                  rollapplyr(x < 0, 5, all, partial = TRUE))
```

Also, the performance is significantly faster. Let me know if you have any other feedback.

**Comment by hadley** [comment]
Looks great, thanks!
