### ISSUE TITLE
Rolling which.min and which.max

### ISSUE THREAD

**Issue by sempeelman** [jjf234/roll#19]
Would you consider adding a rolling version of which.min and which.max? Or, do you see a way to compose this using the already implemented rolling functions?

**Comment by jjf234** [comment]
For an update, I am in the process of implementing efficient algorithms for `roll_min` and `roll_max` functions (see development version for the new `roll_max` function). That will be necessary before the development of something like `roll_idxmax` and `roll_idxmin`.

**Comment by jjf234** [comment]
I have added both `roll_idxmin` and `roll_idxmax` in the development version. Here's an example:

```
# devtools::install_github("jjf234/roll")

library(roll)
library(xts)
library(testthat)

n_vars <- 30
n_obs <- 1500
x <- matrix(rnorm(n_obs * n_vars), nrow = n_obs, ncol = n_vars)

# rolling idxmin ('min_obs = 1' equivalent to 'partial = TRUE')
expect_equivalent(roll_idxmin(x, 5, min_obs = 1),
                  rollapplyr(x, 5, which.min, partial = TRUE))

# rolling idxmax
expect_equivalent(roll_idxmax(x, 5, min_obs = 1),
                  rollapplyr(x, 5, which.max, partial = TRUE))
```
