### ISSUE TITLE
Support vectors?

### ISSUE THREAD

**Issue by hadley** [jjf234/roll#20]
It would be useful if this worked:

``` r
x <- rnorm(100)
roll::roll_mean(x, 5)
#> Error in roll::roll_mean(x, 5): Not a matrix.
```

<sup>Created on 2019-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jjf234** [comment]
Sorry about the delay. For an update, I have added vector support to `roll_mean` and will implement for the other functions too.

**Comment by jjf234** [comment]
I have added vector support for each function in the development version. The reprex works as expected now:

```
# devtools::install_github("jjf234/roll")

x <- rnorm(100)
roll::roll_mean(x, 5)
```
