### ISSUE TITLE
seg faults with roll_min / max

### ISSUE THREAD

**Issue by EmilRehnberg** [jjf234/roll#25]
I have sometimes been experiencing various segfaults / memory issues, when using `roll_min` / `roll_max`. The errors are not happening every run.

E.g.

```
double free or corruption (!prev)
```

or 

```
corrupted size vs. prev_size
```

I've seen other errors as well. However, the same code but with `roll_mean`, `roll_sd` etc. works as expected.

I've tried to find a minimal example for this error but I'm struggling to recreate it in a smaller example. Are you aware of this error? Or do you have an inkling as to what it's about?

**Comment by jangorecki** [comment]
@EmilRehnberg what version are you using? Did you experience same problems using previous stable release 1.1.1? recently package went through multiple changes and it would probably be useful to know if segfault is related to those changes or was there before at the time of 1.1.1.

**Comment by EmilRehnberg** [comment]
I'm running 1.1.3.
I'll try out 1.1.1!

**Comment by EmilRehnberg** [comment]
@jangorecki `roll_min` and `roll_max` aren't available in `1.1.1` :(
But sending in a `matrix` seemed to solve it my initial problem with `roll_min` & `roll_max`. Thanks for the error message in `1.1.1`!

Perhaps it's a good idea to cast the input for `roll_min` & `roll_max` to a matrix. Pls let me know if it's a good idea and if you want a PR for it.

**Comment by jjf234** [comment]
Thanks for letting us know. I understand the difficulty around reproducible examples but could you try to provide one? Even if the example doesn't always segfault, it would be helpful to have more information and guidance to properly debug. Also could you provide the output from `sessionInfo()` too? Alternatively, sometimes something as simple as restarting a clean R session, running `remove.packages("roll")`, and then installing the GitHub version resolves issues too.

**Comment by jjf234** [comment]
Also, the numerical calculations use `RcppParallel` to parallelize the functions and, by default, all the available cores on a machine are used. Instead, could you limit the number of threads used by the `RcppParallel` package, i.e. `setThreadOptions(1)`, and let us know if that resolves the original issue?

**Comment by EmilRehnberg** [comment]
@jjf234 
Sorry, I'm not able to reproduce the error anymore in my code base (the data isn't open neither). I think this bug is pretty obscure and would happen every 8 or so runs when I got the right setup.

I'll close the issue, since I am not able to make a reproducible example.
