### ISSUE TITLE
Adapt functions to work on vectors.

### ISSUE THREAD

**Issue by sempeelmanae** [jjf234/roll#26]
Would you consider modifying the functions so that they allow as input a vector and return a vector. I'm under the impression it would not break any existing code. Today I often end up creating functions as the one below.

```
roll_sum_vec <- function(x, ...) {
   return(roll_sum(as.matrix(x), ...)[,1])
}
```

**Comment by jjf234** [comment]
Vector support was added each to function in version 1.1.3 per #20. Update the `roll` package to either the released version from CRAN or the development version from GitHub (recommended):

```
# install.packages("devtools")
devtools::install_github("jjf234/roll")
```

**Comment by sempeelmanae** [comment]
I see it now. Apologies.
