### ISSUE TITLE
Document online functionality

### ISSUE THREAD

**Issue by samssann** [jjf234/roll#28]
What does it mean to calculate online/offline algorithm?

**Comment by jjf234** [comment]
See the package documentation (`?roll`) to learn more about the motivation for online algorithms in rolling statistics, high-level description of the methodology, trade-offs to consider vs offline algorithms (precision and speed), and academic references, if needed. Also, the Wiki on [algorithms for calculating variance](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance) is useful too.

**Comment by jjf234** [comment]
Let me know if I can clarify the documentation for future users, otherwise will close this issue.
