### ISSUE TITLE
[DOCS] - type of quantile algorithm

### ISSUE THREAD

**Issue by Eluvias** [jjf234/roll#30]
It's great to see that the new version will include a rolling quantile implementation. Is it possible to document which type of algorithm is used; it looks like Type 2.

See also:
 - [caTools - runquantile()](https://www.rdocumentation.org/packages/caTools/versions/1.17.1/topics/runquantile)
- [Armadillio - quantile](http://arma.sourceforge.net/docs.html#quantile)
- [ stats - quantile](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/quantile)

**Comment by jjf234** [comment]
Thanks for the feedback. I have updated the documentation in the development version.
