### ISSUE TITLE
Crash in roll_max with vectors of lenth around 545

### ISSUE THREAD

**Issue by lukasz-bednarz-reddeersystems** [jjf234/roll#32]
roll::roll_max(rep(1,545), 10)

causes crash in R-4.0.2 with roll v1.1.4

**Comment by jjf234** [comment]
Thanks for the reprex. I have fixed the issue in the development version:

```
# install.packages("devtools")
devtools::install_github("jjf234/roll")
```

**Comment by lukasz-bednarz-reddeersystems** [comment]
Hi,

When do you think the CRAN version with fix might be available?

**Comment by jjf234** [comment]
I would like to update the CRAN version in the next week or two. Could you confirm the fix resolves the issue?

**Comment by lukasz-bednarz-reddeersystems** [comment]
Yes, the fix is working.
