### ISSUE TITLE
roll_rank( )

### ISSUE THREAD

**Issue by xiaoxxliu** [jjf234/roll#33]
Thanks for the great package, I've benefitted from it a lot.

Would you consider adding a rolling version of rank ?

It works like :

`x=rnorm(n)`
`sapply(width:n,function(i) tail(rank(x[(i-width+1):i]),1))`

**Comment by jjf234** [comment]
The current list of functions is mostly from my own survey of rolling statistics that focuses on common use cases and demand, so could you share links to other GH repos or SO questions that discuss something like `roll_rank`? For more background, the function implementations in `roll` need to offer an "online" algorithm, which is more difficult, so need to consider the cost-benefit of each function too.

**Comment by jjf234** [comment]
This issue has been closed because there has been no response to my request for more information. Please feel free to reopen if you have or find the answers needed though.
