### ISSUE TITLE
R Packages: roll vs rollregres

### ISSUE THREAD

**Issue by supermarco99** [jjf234/roll#36]
Hi !

I was working on both packages and realised that the coefficients are not the same. Please, can someone confirm or not ?

It is important because Roll package computes standard erros while Rollregress doesn't.

I look forward any help to find a package on r that computes rolling coefficients, standard errors and R².

Thanks a lot.

**Comment by jjf234** [comment]
The `rollRegress` package includes a vignette with a comparison to the `roll` package that shows the coefficients are equivalent here: https://cran.r-project.org/web/packages/rollRegres/vignettes/Comparisons.html. Otherwise could you please provide a reproducible example?

**Comment by supermarco99** [comment]
> The `rollRegress` package includes a vignette with a comparison to the `roll` package that shows the coefficients are equivalent here: https://cran.r-project.org/web/packages/rollRegres/vignettes/Comparisons.html. Otherwise could you please provide a reproducible example?

Thanks a lot for the link. Let me try and run again the comparison test and come back either with a reproductible example or a confirmation that the results is the same.

**Comment by supermarco99** [comment]
Hello, i confirm the vignette. Both provide same results. I did a mistake in the roll package by inverting Y and X. Sorry and Many thanks for your response.
