### ISSUE TITLE
`partial` support

### ISSUE THREAD

**Issue by fdetsch** [jjf234/roll#37]
Would it be possible to add a `partial` argument to all suited **roll** functions similar to `zoo::rollapply()`? Take the following **zoo** based example: 

```r
## sample data
set.seed(
  1899
)

x = sample(
  1:5
  , size = 10
  , replace = TRUE
)

## compute rolling variance
zoo::rollapply(
  x
  , width = 3
  , FUN = var
  , partial = TRUE
)
# [1] 2.0000000 2.3333333 2.3333333 4.3333333 5.3333333 5.3333333 4.0000000 2.3333333 0.3333333
# [10] 0.0000000
```

The closest I get with **roll** would currently be

```r
roll::roll_var(
  x
  , width = 3
  , min_obs = 1
)
# [1]        NA 2.0000000 2.3333333 2.3333333 4.3333333 5.3333333 5.3333333 4.0000000 2.3333333
# [10] 0.3333333
```

which adds a leading `NA` and omits the last variance value. Ultimately, I would want to have the same output as obtained from `zoo::rollapply()`.

Am I missing something here? My data set has `> 1e6` data points, so a **Rcpp** based approach would be highly appreciated from a computational point of view. Unfortunately, **RcppRoll** doesn't handle `partial` window indexes either, see [#18](https://github.com/kevinushey/RcppRoll/issues/18).

**Comment by fdetsch** [comment]
Of course, I could always do something like

```r
width = 3

na.omit(
  roll::roll_var(
    c(x, rep(NA, floor(width / 2)))
    , width = width
    , min_obs = 1
  )
)
```

but this feels kinda hacky 😅

**Comment by jjf234** [comment]
Partial windows are supported in the `roll` package via the `min_obs` argument. In order to match the results above, instead you need to set `align = "right"` in the `rollapply` function:

```{r}
zoo::rollapply(
  x
  , width = 3
  , FUN = var
  , partial = TRUE
  , align = "right"
)
 [1]        NA 2.0000000 2.3333333 2.3333333 4.3333333 5.3333333 5.3333333 4.0000000 2.3333333
[10] 0.3333333

roll::roll_var(
  x
  , width = 3
  , min_obs = 1
)
 [1]        NA 2.0000000 2.3333333 2.3333333 4.3333333 5.3333333 5.3333333 4.0000000 2.3333333
[10] 0.3333333
```

**Comment by fdetsch** [comment]
Thing is, I need the `align = "center"` default behavior from `zoo::rollapply()`. Judging from your response, the integration of such an option is not planned for **roll**? If not, I could simply stick with the above workaround.

**Comment by jjf234** [comment]
Thanks for the feedback. To keep the discussion focused, feel free to open a new issue to request the `align` argument. I don't have plans to support it but we can see whether there's demand or collaborators that want to help.
