### ISSUE TITLE
roll with time interval not with width

### ISSUE THREAD

**Issue by shenqixue** [jjf234/roll#39]
I have a panel data with stock id and time, I want to compute the average price over a time interval. Since the time is irregular, it is more efficient to roll with time interval, not with width. Could the author add the functionality? And similar problem for roll_lm. Thank you very much.

**Comment by jjf234** [comment]
Thanks for the feedback. For background, the `roll` package was designed for vectors or matrices where rows are observations and columns are variables, so you would need to reshape the panel data and then either pad the time-series with NA’s or convert to a frequency lower than the given object (see `?xts::to_period`). I currently don't have plans to support it explicitly but I'm open to provide guidance to collaborators who want to help.
