### ISSUE TITLE
Add roll_median

### ISSUE THREAD

**Issue by mdancho84** [jjf234/roll#4]
Looking for a rolling median `roll_median` function. Doesn't look like the most recent CRAN version includes this. Let me know if you are interested in adding.

Thanks, Matt

**Comment by peleonard** [comment]
@mdancho84 I wrote a package about roll_median. You can try if you like.

**Comment by jjf234** [comment]
Thanks for the feedback. I think a more general development is to create a rolling quantile function where min, max, and median are special cases. Would be a nice enhancement.

**Comment by jjf234** [comment]
I have added `roll_median` in the development version:

```
# install.packages("devtools")
devtools::install_github("jjf234/roll")
```
