### ISSUE TITLE
roll_lm residual standard error

### ISSUE THREAD

**Issue by shenqixue** [jjf234/roll#40]
I am sorry to bother you again. I am heavily relying on your roll_lm function. I am doing pairs trading in stock market, so I need to analyze the residuals, such as the residual standard errors. Is it convenient to add the functionality? or could you just output the residual as a list as lm does in base R. 
          I have try to read you code. But my cpp coding ability is very weak, so it is impossible for me to solve this problem on my own. Your help will be much appreciated.

**Comment by jjf234** [comment]
Thanks for the feedback but the `roll` package already does the heavy-lifting to get you the inputs for what you need to get the residual standard error. Specifically, you can calculate the value using the existing `roll_lm` and `roll_var` functions:

```
library(roll)
library(testthat)
library(xts)

n <- 15
width <- 5
x <- rnorm(n)
y <- rnorm(n)

lm_sigma <- function(z) {
  
  fit <- lm(formula = y ~ x, data = as.data.frame(z))
  return(sigma(fit))

}

r_lm_sigma <- rollapply(data = cbind(x, y), width,
                        FUN = lm_sigma, by.column = FALSE,
                        align = "right")

roll_lm_sigma <- sqrt((1 - roll_lm(x, y, width)$r.squared) *
                        roll_var(y, width) * (width - 1) / (width - 2))

expect_equivalent(r_lm_sigma, na.omit(roll_lm_sigma))
```
