### ISSUE TITLE
[Feature Request] Add flag for sample and population standard deviations

### ISSUE THREAD

**Issue by ckatsulis** [jjf234/roll#6]
Can you add the flag to calculate sd of both sample and population, essentially making the adjustment for N in the averaging to be N-1?

Thanks

**Comment by jjf234** [comment]
The `roll` functions use denominator `n - 1` to give an unbiased estimator of the standard deviation, like the base functions (see `?sd`). Technically it’s one minus the sum of squares of the weights, but if the weights are the default then the divisor `n – 1` is obtained. My goal is to be consistent with base functions so I don’t have plans to add support for biased estimates but I can clarify the documentation for future users to avoid confusion. If needed, it is straightforward to apply Bessel’s correction for standard deviation though: https://stackoverflow.com/a/6457804.
