### ISSUE TITLE
Add p-values for coefficients for roll_lm

### ISSUE THREAD

**Issue by ab4es** [jjf234/roll#7]
Would it be at all possible to add p-values (Pr(>|t|)) to the output of roll_lm? It would be really useful when performing the rolling regression to observe if variables remained statistically significant through the regression period.

Thanks!

**Comment by jjf234** [comment]
Thanks, I've received similar feedback from others so adding standard errors is on my list of enhancements I'd like to do too.

**Comment by jjf234** [comment]
Standard errors have been added in the development version:

```
# install.packages("devtools")
devtools::install_github("jjf234/roll")
```
