### ISSUE TITLE
roll_cov

### ISSUE THREAD

**Issue by dedduchenkov** [jjf234/roll#9]
I tried this function on a stock returns dataset and surprisingly got an output of NA only. I thought there were some returns missing in my dataset, but then I noticed, this is even more surprisingly, that the simple example given here https://cran.r-project.org/web/packages/roll/roll.pdf provides the same NA output. What could the cause be?

**Comment by jjf234** [comment]
It works as expected for me so could you run the following and let me know the output, or provide a reproducible example?
```
n_vars <- 4
n_obs <- 10
set.seed(1234)
data <- matrix(rnorm(n_obs * n_vars), nrow = n_obs, ncol = n_vars)

# rolling covariance matrices
result <- roll_cov(data, 5)

> dim(result)
[1]  4  4 10

> result[ , , 10]
[,1]       [,2]       [,3]        [,4]
[1,]  0.28479480 -0.2306381 -0.2102778 -0.06993086
[2,] -0.23063805  1.9100651 -0.3558404  0.40896502
[3,] -0.21027778 -0.3558404  0.6823256 -0.21317050
[4,] -0.06993086  0.4089650 -0.2131705  0.56996516
```

**Comment by jjf234** [comment]
I'd like to help but, because there has been no response to my request for more information, this issue has been closed. Please feel free to reopen if you have or find the answers needed though.
